### ISSUE TITLE
chore: check backend `docker-compose.dev` context

### ISSUE THREAD

**Issue by kaljarv** [OpenVAA/voting-advice-application#617]
The shared module is no longer symlinked so this part ought to be able to be changed:

```yaml
    build:
      # Context includes the root of the repository so that we can expose shared/ module.
      context: ../../
      dockerfile: backend/vaa-strapi/Dockerfile
      target: development
```
